---
spring:
  profiles: primary
  application:
    name: ${spring.profiles.active}
server:
  port: 8011
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-secondary:8012/eureka/,http://eureka-teritiary:8013/eureka/
---
spring:
  profiles: secondary
  application:
    name: ${spring.profiles.active}
server:
  port: 8012
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-teritiary:8013/eureka/   
---
spring:
  profiles: teritiary
  application:
    name: ${spring.profiles.active}
server:
  port: 8013
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/
